# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-01-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeonboardinfo',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
